import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ConfigProvider } from 'antd';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * RootLayout : balises <html> / <body> obligatoires pour Next.js.
 * Le ConfigProvider Ant Design englobe toute l'application pour les thèmes.
 */
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body style={{ margin: 0 }}>
        <ConfigProvider
              theme={{
                token: {
                  colorPrimary: '#3D207A',
                  colorLink: '#3D207A',
                  colorLinkHover: '#5633A4',
                  colorLinkActive: '#2A1356',
                },
                components: {
                  Button: {
                    defaultShadow: 'none',
                    primaryShadow: 'none',
                    dangerShadow: 'none',
                  },
                },
              }}
        >
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
}
